// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for about documents */
interface AboutDocumentData {
    /**
     * title field in *about*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * background field in *about*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: about.background
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background: prismicT.ColorField;
    /**
     * foreground field in *about*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: about.foreground
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    foreground: prismicT.ColorField;
    /**
     * introduction field in *about*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.introduction
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    introduction: prismicT.RichTextField;
    /**
     * profile field in *about*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about.profile
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    profile: prismicT.ImageField<null>;
    /**
     * Slice Zone (`body`) field in *about*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: about.body[]
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismicT.SliceZone<AboutDocumentDataBodySlice>;
    /**
     * meta title field in *about*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.meta_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismicT.KeyTextField;
    /**
     * meta description field in *about*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.meta_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * meta image field in *about*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about.meta_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismicT.ImageField<null>;
}
/**
 * Primary content in about → Slice Zone (`body`) → about section → Primary
 *
 */
interface AboutDocumentDataBodyAboutSectionSlicePrimary {
    /**
     * title field in *about → Slice Zone (`body`) → about section → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.body[].about_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * image field in *about → Slice Zone (`body`) → about section → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about.body[].about_section.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<null>;
    /**
     * description field in *about → Slice Zone (`body`) → about section → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.body[].about_section.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in about → Slice Zone (`body`) → about section → Items
 *
 */
export interface AboutDocumentDataBodyAboutSectionSliceItem {
    /**
     * link text field in *about → Slice Zone (`body`) → about section → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about.body[].about_section.items[].link_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_text: prismicT.KeyTextField;
    /**
     * link url field in *about → Slice Zone (`body`) → about section → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: about.body[].about_section.items[].link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
}
export type AboutDocumentDataBodyAboutSectionSlice = prismicT.Slice<"about_section", Simplify<AboutDocumentDataBodyAboutSectionSlicePrimary>, Simplify<AboutDocumentDataBodyAboutSectionSliceItem>>;
/**
 * Slice for *about → Slice Zone (`body`)*
 *
 */
type AboutDocumentDataBodySlice = AboutDocumentDataBodyAboutSectionSlice;
/**
 * about document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = "en-us"> = prismicT.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;
/** Content for home documents */
interface HomeDocumentData {
    /**
     * background field in *home*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: home.background
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background: prismicT.ColorField;
    /**
     * foreground field in *home*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: home.foreground
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    foreground: prismicT.ColorField;
    /**
     * Slice Zone (`body`) field in *home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.body[]
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismicT.SliceZone<HomeDocumentDataBodySlice>;
    /**
     * meta title field in *home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.meta_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismicT.KeyTextField;
    /**
     * meta description field in *home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.meta_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * meta image field in *home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.meta_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismicT.ImageField<null>;
    /**
     * header links field in *home*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: home.header_links[]
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    header_links: prismicT.GroupField<Simplify<HomeDocumentDataHeaderLinksItem>>;
}
/**
 * Item in home → Slice Zone (`body`) → home items → Items
 *
 */
export interface HomeDocumentDataBodyHomeItemsSliceItem {
    /**
     * items field in *home → Slice Zone (`body`) → home items → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: home.body[].home_items.items[].items
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    items: prismicT.RelationField<"page">;
}
export type HomeDocumentDataBodyHomeItemsSlice = prismicT.Slice<"home_items", Record<string, never>, Simplify<HomeDocumentDataBodyHomeItemsSliceItem>>;
/**
 * Slice for *home → Slice Zone (`body`)*
 *
 */
type HomeDocumentDataBodySlice = HomeDocumentDataBodyHomeItemsSlice;
/**
 * Item in home → header links
 *
 */
export interface HomeDocumentDataHeaderLinksItem {
    /**
     * text field in *home → header links*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home.header_links[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text: prismicT.KeyTextField;
    /**
     * url field in *home → header links*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: home.header_links[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = "en-us"> = prismicT.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;
/** Content for page documents */
interface PageDocumentData {
    /**
     * title field in *page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * background field in *page*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: page.background
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background: prismicT.ColorField;
    /**
     * foreground field in *page*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: page.foreground
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    foreground: prismicT.ColorField;
    /**
     * Slice Zone (`body`) field in *page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[]
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    body: prismicT.SliceZone<PageDocumentDataBodySlice>;
    /**
     * meta title field in *page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismicT.KeyTextField;
    /**
     * meta description field in *page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * meta image field in *page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismicT.ImageField<null>;
}
/**
 * Primary content in page → Slice Zone (`body`) → Horizontal → Primary
 *
 */
interface PageDocumentDataBodyHorizontalSlicePrimary {
    /**
     * background field in *page → Slice Zone (`body`) → Horizontal → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].horizontal.primary.background
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background: prismicT.ColorField;
    /**
     * foreground field in *page → Slice Zone (`body`) → Horizontal → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].horizontal.primary.foreground
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    foreground: prismicT.ColorField;
}
/**
 * Item in page → Slice Zone (`body`) → Horizontal → Items
 *
 */
export interface PageDocumentDataBodyHorizontalSliceItem {
    /**
     * image field in *page → Slice Zone (`body`) → Horizontal → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].horizontal.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<null>;
}
export type PageDocumentDataBodyHorizontalSlice = prismicT.Slice<"horizontal", Simplify<PageDocumentDataBodyHorizontalSlicePrimary>, Simplify<PageDocumentDataBodyHorizontalSliceItem>>;
/**
 * Primary content in page → Slice Zone (`body`) → Grid → Primary
 *
 */
interface PageDocumentDataBodyGridSlicePrimary {
    /**
     * background field in *page → Slice Zone (`body`) → Grid → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].grid.primary.background
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    background: prismicT.ColorField;
    /**
     * foreground field in *page → Slice Zone (`body`) → Grid → Primary*
     *
     * - **Field Type**: Color
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].grid.primary.foreground
     * - **Documentation**: https://prismic.io/docs/core-concepts/color
     *
     */
    foreground: prismicT.ColorField;
    /**
     * container size field in *page → Slice Zone (`body`) → Grid → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: large
     * - **API ID Path**: page.body[].grid.primary.container_size
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    container_size: prismicT.SelectField<"large" | "medium", "filled">;
}
/**
 * Item in page → Slice Zone (`body`) → Grid → Items
 *
 */
export interface PageDocumentDataBodyGridSliceItem {
    /**
     * image field in *page → Slice Zone (`body`) → Grid → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.body[].grid.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<null>;
}
export type PageDocumentDataBodyGridSlice = prismicT.Slice<"grid", Simplify<PageDocumentDataBodyGridSlicePrimary>, Simplify<PageDocumentDataBodyGridSliceItem>>;
/**
 * Slice for *page → Slice Zone (`body`)*
 *
 */
type PageDocumentDataBodySlice = PageDocumentDataBodyHorizontalSlice | PageDocumentDataBodyGridSlice;
/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = "en-us"> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
