on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '**.json'
      - 'src/**'
jobs:
  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: install dependencies
        run: yarn install
      - name: run type checker
        run: yarn check:type
